<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque 
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.secret.data.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.secret.data.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.secret.data.MYSQL_PASSWORD }}
=======
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque 
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.secret.data.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.secret.data.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.secret.data.MYSQL_PASSWORD }}
>>>>>>> 95a8bc319c2315d8885f813c226b2a5dccb77e37
  SECRET_KEY: {{ .Values.secret.data.SECRET_KEY }}