<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
      component: web
  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
        component: web
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "my-app.fullname" . }}-dbsvc 3306; do
                echo "Waiting for database..."
                sleep 2
              done
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "development"
            - name: DB_HOST
              value: "{{ include "my-app.fullname" . }}-dbsvc"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MYSQL_DATABASE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: SECRET_KEY


          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-websvc
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
      component: web
  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
        component: web
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "my-app.fullname" . }}-dbsvc 3306; do
                echo "Waiting for database..."
                sleep 2
              done
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "development"
            - name: DB_HOST
              value: "{{ include "my-app.fullname" . }}-dbsvc"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MYSQL_DATABASE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: SECRET_KEY


          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-websvc
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
>>>>>>> 95a8bc319c2315d8885f813c226b2a5dccb77e37
    component: web